// A QR encoder, byte mode, versions 1-13, EC levels L and M.
//
// Written out rather than pulled in for the same reason as server/base58.mjs:
// this project ships no dependencies, and a payment QR is not worth breaking
// that for. The scope is deliberately narrow -- it encodes one kind of thing,
// a Solana Pay URL of about 180 bytes, so numeric/alphanumeric/kanji modes and
// versions past 13 are simply absent rather than half-implemented.
//
// A note on the failure mode, because it is the reassuring part: a bug here
// cannot send someone's money to the wrong place. Every QR carries Reed-Solomon
// parity over its own contents, so a wrongly-built symbol fails to scan; it
// does not quietly decode to a different valid address.
//
// Structure, in the order the code below builds it:
//   1. the payload as data codewords  (mode, length, bytes, terminator, padding)
//   2. Reed-Solomon parity over those, per block
//   3. blocks interleaved into the final codeword stream
//   4. codewords painted into the matrix in the zigzag order, around the
//      function patterns
//   5. all eight masks tried, scored by the standard penalty rules, best kept
//   6. format and (for version >= 7) version information written in

// Total data codewords, and how they are split into Reed-Solomon blocks.
// [ecCodewordsPerBlock, group1Blocks, group1DataCodewords, group2Blocks, group2DataCodewords]
const EC_TABLE = {
  L: {
    1: [7, 1, 19, 0, 0], 2: [10, 1, 34, 0, 0], 3: [15, 1, 55, 0, 0],
    4: [20, 1, 80, 0, 0], 5: [26, 1, 108, 0, 0], 6: [18, 2, 68, 0, 0],
    7: [20, 2, 78, 0, 0], 8: [24, 2, 97, 0, 0], 9: [30, 2, 116, 0, 0],
    10: [18, 2, 68, 2, 69], 11: [20, 4, 81, 0, 0], 12: [24, 2, 92, 2, 93],
    13: [26, 4, 107, 0, 0],
  },
  M: {
    1: [10, 1, 16, 0, 0], 2: [16, 1, 28, 0, 0], 3: [26, 1, 44, 0, 0],
    4: [18, 2, 32, 0, 0], 5: [24, 2, 43, 0, 0], 6: [16, 4, 27, 0, 0],
    7: [18, 4, 31, 0, 0], 8: [22, 2, 38, 2, 39], 9: [22, 3, 36, 2, 37],
    10: [26, 4, 43, 1, 44], 11: [30, 1, 50, 4, 51], 12: [22, 6, 39, 2, 40],
    13: [22, 8, 33, 1, 34],
  },
};

// Centres of the alignment patterns. The corners where finder patterns already
// sit are skipped when they are placed.
const ALIGNMENT = {
  1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30], 6: [6, 34],
  7: [6, 22, 38], 8: [6, 24, 42], 9: [6, 26, 46], 10: [6, 28, 50],
  11: [6, 30, 54], 12: [6, 32, 58], 13: [6, 34, 62],
};

const EC_BITS = { L: 0b01, M: 0b00 }; // as they appear in the format string

// ---------- GF(256) ----------
// The field QR uses, generated by x^8 + x^4 + x^3 + x^2 + 1 (0x11d). Log and
// antilog tables turn multiplication into addition, which is what makes the
// polynomial arithmetic below readable.
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
})();

function gfMul(a, b) {
  if (a === 0 || b === 0) return 0;
  return EXP[LOG[a] + LOG[b]];
}

// The generator polynomial for `degree` error-correction codewords:
// (x - a^0)(x - a^1)...(x - a^(degree-1))
function generatorPoly(degree) {
  let poly = [1];
  for (let i = 0; i < degree; i++) {
    const next = new Array(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];
      next[j + 1] ^= gfMul(poly[j], EXP[i]);
    }
    poly = next;
  }
  return poly;
}

// Polynomial long division; the remainder is the error-correction codewords.
function reedSolomon(data, ecCount) {
  const gen = generatorPoly(ecCount);
  const rem = new Array(ecCount).fill(0);
  for (const byte of data) {
    const factor = byte ^ rem[0];
    rem.shift();
    rem.push(0);
    if (factor !== 0) {
      for (let i = 0; i < ecCount; i++) rem[i] ^= gfMul(gen[i + 1], factor);
    }
  }
  return rem;
}

// ---------- payload -> codewords ----------

function dataCapacity(version, ec) {
  const [, g1, g1d, g2, g2d] = EC_TABLE[ec][version];
  return g1 * g1d + g2 * g2d;
}

function chooseVersion(byteLength, ec) {
  for (let v = 1; v <= 13; v++) {
    // 4 bits of mode + the character count (8 bits up to version 9, 16 after)
    const countBits = v <= 9 ? 8 : 16;
    const needed = Math.ceil((4 + countBits + byteLength * 8) / 8);
    if (needed <= dataCapacity(v, ec)) return v;
  }
  return null;
}

function buildDataCodewords(bytes, version, ec) {
  const countBits = version <= 9 ? 8 : 16;
  const bits = [];
  const push = (value, length) => {
    for (let i = length - 1; i >= 0; i--) bits.push((value >> i) & 1);
  };

  push(0b0100, 4);              // byte mode
  push(bytes.length, countBits);
  for (const b of bytes) push(b, 8);

  const capacityBits = dataCapacity(version, ec) * 8;
  // Terminator: up to four zero bits, but never past the end.
  push(0, Math.min(4, capacityBits - bits.length));
  while (bits.length % 8 !== 0) bits.push(0);

  const codewords = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
    codewords.push(byte);
  }
  // Pad bytes alternate 236/17 by specification -- the pattern matters only in
  // that decoders expect it, but it is what the standard says.
  const pad = [0xec, 0x11];
  let i = 0;
  while (codewords.length < dataCapacity(version, ec)) codewords.push(pad[i++ % 2]);
  return codewords;
}

// Blocks are interleaved: first codeword of every block, then the second of
// every block, and so on, then the same for the parity. That is what makes a
// scratch across the symbol damage a little of each block rather than
// destroying one outright.
function interleave(codewords, version, ec) {
  const [ecPerBlock, g1, g1d, g2, g2d] = EC_TABLE[ec][version];
  const blocks = [];
  let offset = 0;
  for (let i = 0; i < g1; i++) { blocks.push(codewords.slice(offset, offset + g1d)); offset += g1d; }
  for (let i = 0; i < g2; i++) { blocks.push(codewords.slice(offset, offset + g2d)); offset += g2d; }

  const ecBlocks = blocks.map((b) => reedSolomon(b, ecPerBlock));
  const out = [];
  const maxData = Math.max(...blocks.map((b) => b.length));
  for (let i = 0; i < maxData; i++) {
    for (const b of blocks) if (i < b.length) out.push(b[i]);
  }
  for (let i = 0; i < ecPerBlock; i++) {
    for (const b of ecBlocks) out.push(b[i]);
  }
  return out;
}

// ---------- the matrix ----------

function emptyMatrix(size) {
  return Array.from({ length: size }, () => new Array(size).fill(null));
}

function placeFinder(m, row, col) {
  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const rr = row + r, cc = col + c;
      if (rr < 0 || cc < 0 || rr >= m.length || cc >= m.length) continue;
      const inRing = (r >= 0 && r <= 6 && (c === 0 || c === 6)) || (c >= 0 && c <= 6 && (r === 0 || r === 6));
      const inCore = r >= 2 && r <= 4 && c >= 2 && c <= 4;
      m[rr][cc] = inRing || inCore ? 1 : 0;
    }
  }
}

function placeAlignment(m, version) {
  const centres = ALIGNMENT[version];
  const last = m.length - 1;
  for (const r of centres) {
    for (const c of centres) {
      // The three corners already hold finder patterns.
      if ((r === 6 && c === 6) || (r === 6 && c === last - 6) || (r === last - 6 && c === 6)) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          const ring = Math.max(Math.abs(dr), Math.abs(dc));
          m[r + dr][c + dc] = ring === 1 ? 0 : 1;
        }
      }
    }
  }
}

function placeTiming(m) {
  for (let i = 8; i < m.length - 8; i++) {
    const v = i % 2 === 0 ? 1 : 0;
    if (m[6][i] === null) m[6][i] = v;
    if (m[i][6] === null) m[i][6] = v;
  }
}

// Where format and version information will go. Reserved before data is laid
// out so the zigzag skips it, then filled in at the end.
function reserveInfoAreas(m, version) {
  const size = m.length;
  for (let i = 0; i < 9; i++) {
    if (m[8][i] === null) m[8][i] = 0;
    if (m[i][8] === null) m[i][8] = 0;
  }
  for (let i = 0; i < 8; i++) {
    if (m[8][size - 1 - i] === null) m[8][size - 1 - i] = 0;
    if (m[size - 1 - i][8] === null) m[size - 1 - i][8] = 0;
  }
  m[size - 8][8] = 1; // the always-dark module
  if (version >= 7) {
    for (let i = 0; i < 6; i++) {
      for (let j = 0; j < 3; j++) {
        m[size - 11 + j][i] = 0;
        m[i][size - 11 + j] = 0;
      }
    }
  }
}

// Up the right-hand column pair, down the next, skipping the vertical timing
// column. Every module the function patterns did not claim gets one bit.
function placeData(m, codewords) {
  const size = m.length;
  const bits = [];
  for (const cw of codewords) {
    for (let i = 7; i >= 0; i--) bits.push((cw >> i) & 1);
  }

  let bit = 0;
  let upward = true;
  for (let right = size - 1; right > 0; right -= 2) {
    if (right === 6) right = 5; // the timing column is not part of the zigzag
    for (let step = 0; step < size; step++) {
      const row = upward ? size - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (m[row][col] !== null) continue;
        m[row][col] = bit < bits.length ? bits[bit] : 0;
        bit++;
      }
    }
    upward = !upward;
  }
}

const MASKS = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

// The standard's four penalty rules. Their purpose is to avoid symbols that
// look like the finder patterns, or that have large flat areas a scanner
// struggles to lock onto.
function penalty(m) {
  const size = m.length;
  let score = 0;

  // Rule 1: runs of five or more of the same colour, in both directions.
  for (const transposed of [false, true]) {
    for (let a = 0; a < size; a++) {
      let run = 1;
      for (let b = 1; b < size; b++) {
        const cur = transposed ? m[b][a] : m[a][b];
        const prev = transposed ? m[b - 1][a] : m[a][b - 1];
        if (cur === prev) {
          run++;
          if (run === 5) score += 3;
          else if (run > 5) score += 1;
        } else run = 1;
      }
    }
  }

  // Rule 2: every 2x2 block of one colour.
  for (let r = 0; r < size - 1; r++) {
    for (let c = 0; c < size - 1; c++) {
      const v = m[r][c];
      if (v === m[r][c + 1] && v === m[r + 1][c] && v === m[r + 1][c + 1]) score += 3;
    }
  }

  // Rule 3: the finder-like 1:1:3:1:1 sequence with four light modules beside it.
  const A = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
  const B = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];
  for (const transposed of [false, true]) {
    for (let a = 0; a < size; a++) {
      for (let b = 0; b <= size - 11; b++) {
        let matchA = true, matchB = true;
        for (let k = 0; k < 11; k++) {
          const v = transposed ? m[b + k][a] : m[a][b + k];
          if (v !== A[k]) matchA = false;
          if (v !== B[k]) matchB = false;
        }
        if (matchA) score += 40;
        if (matchB) score += 40;
      }
    }
  }

  // Rule 4: how far the proportion of dark modules strays from half.
  let dark = 0;
  for (const row of m) for (const v of row) if (v) dark++;
  const percent = (dark * 100) / (size * size);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;
  return score;
}

// 15-bit BCH(15,5) over the 5 data bits, then XOR with the standard's mask so
// an all-zero format string is not all-zero on the symbol.
function formatBits(ec, mask) {
  const data = (EC_BITS[ec] << 3) | mask;
  let rem = data << 10;
  for (let i = 14; i >= 10; i--) {
    if ((rem >> i) & 1) rem ^= 0b10100110111 << (i - 10);
  }
  return ((data << 10) | rem) ^ 0b101010000010010;
}

// 18-bit BCH(18,6), used only from version 7 up. The generator is
// x^12 + x^11 + x^10 + x^9 + x^8 + x^5 + x^2 + 1, which is thirteen bits wide
// -- not the ten-bit format-information generator, which is a different code
// entirely and produces version strings that no scanner will accept.
// Checked against the published version-information table; see
// scripts/test-qr.mjs.
function versionBits(version) {
  let rem = version << 12;
  for (let i = 17; i >= 12; i--) {
    if ((rem >> i) & 1) rem ^= 0b1111100100101 << (i - 12);
  }
  return (version << 12) | rem;
}

function writeFormat(m, ec, mask) {
  const bits = formatBits(ec, mask);
  const size = m.length;
  const get = (i) => (bits >> i) & 1;

  // Copy one: around the top-left finder.
  for (let i = 0; i <= 5; i++) m[8][i] = get(i);
  m[8][7] = get(6);
  m[8][8] = get(7);
  m[7][8] = get(8);
  for (let i = 9; i <= 14; i++) m[14 - i][8] = get(i);

  // Copy two: split between the other two corners, so damage to one corner
  // does not take the format information with it.
  for (let i = 0; i <= 7; i++) m[size - 1 - i][8] = get(i);
  for (let i = 8; i <= 14; i++) m[8][size - 15 + i] = get(i);
  m[size - 8][8] = 1;
}

function writeVersion(m, version) {
  if (version < 7) return;
  const bits = versionBits(version);
  const size = m.length;
  for (let i = 0; i < 18; i++) {
    const bit = (bits >> i) & 1;
    const r = Math.floor(i / 3);
    const c = i % 3;
    m[size - 11 + c][r] = bit;
    m[r][size - 11 + c] = bit;
  }
}

/**
 * Encodes `text` and returns { size, modules, version, ec, mask }, where
 * `modules` is a size x size array of 0/1.
 */
export function encodeQR(text, { ec = "M" } = {}) {
  const bytes = new TextEncoder().encode(text);
  let level = ec;
  let version = chooseVersion(bytes.length, level);
  if (version === null && level === "M") {
    // Too long for the sturdier level; drop to L rather than refuse outright.
    level = "L";
    version = chooseVersion(bytes.length, level);
  }
  if (version === null) throw new Error(`too long for this encoder: ${bytes.length} bytes`);

  const codewords = interleave(buildDataCodewords(bytes, version, level), version, level);
  const size = version * 4 + 17;

  const base = emptyMatrix(size);
  placeFinder(base, 0, 0);
  placeFinder(base, 0, size - 7);
  placeFinder(base, size - 7, 0);
  placeAlignment(base, version);
  placeTiming(base);

  // Which modules are function patterns, recorded before the data goes in --
  // masking must leave them alone.
  const reserved = emptyMatrix(size);
  reserveInfoAreas(base, version);
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) reserved[r][c] = base[r][c] !== null;
  }

  placeData(base, codewords);

  let best = null;
  for (let mask = 0; mask < 8; mask++) {
    const candidate = base.map((row) => row.slice());
    for (let r = 0; r < size; r++) {
      for (let c = 0; c < size; c++) {
        if (!reserved[r][c] && MASKS[mask](r, c)) candidate[r][c] ^= 1;
      }
    }
    writeFormat(candidate, level, mask);
    writeVersion(candidate, version);
    const score = penalty(candidate);
    if (!best || score < best.score) best = { score, mask, modules: candidate };
  }

  return { size, modules: best.modules, version, ec: level, mask: best.mask };
}

/**
 * Renders to an SVG string. SVG rather than canvas so it stays sharp at any
 * size and can be dropped straight into innerHTML.
 */
export function qrSvg(text, { ec = "M", quiet = 4, dark = "#101418", light = "#ffffff" } = {}) {
  const { size, modules } = encodeQR(text, { ec });
  const total = size + quiet * 2;
  const parts = [];
  for (let r = 0; r < size; r++) {
    // Runs of dark modules become one rect, which cuts the node count by
    // roughly half and keeps the markup small enough to inline.
    let c = 0;
    while (c < size) {
      if (!modules[r][c]) { c++; continue; }
      let run = 1;
      while (c + run < size && modules[r][c + run]) run++;
      parts.push(`<rect x="${c + quiet}" y="${r + quiet}" width="${run}" height="1"/>`);
      c += run;
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" shape-rendering="crispEdges" role="img" aria-label="Payment QR code">`
    + `<rect width="${total}" height="${total}" fill="${light}"/>`
    + `<g fill="${dark}">${parts.join("")}</g></svg>`;
}
